required = [
  "github.com/golang/protobuf/protoc-gen-go",
]

[[constraint]]
  version = "1.3.0"
  name = "github.com/golang/protobuf"

[[constraint]]
  branch = "master"
  name = "google.golang.org/genproto"

[[constraint]]
  branch = "add-grpc-web-client"
  name = "google.golang.org/grpc"
  source = "github.com/johanbrandhorst/grpc-go"

[[override]]
  branch = "add-grpc-web-client"
  name = "google.golang.org/grpc"
  source = "github.com/johanbrandhorst/grpc-go"

[[constraint]]
  version = "0.9.1"
  name = "github.com/improbable-eng/grpc-web"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
